import express from "express";
import PDFDocument from "pdfkit";
import Assessment from "../models/Assessment.js";

const router = express.Router();

router.get("/download/:id", async (req, res) => {
  try {
    const assessment = await Assessment.findById(req.params.id);

    if (!assessment) {
      return res.status(404).json({ message: "Assessment not found" });
    }

    const doc = new PDFDocument({ margin: 40 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=Aurevia_Health_Audit.pdf`
    );

    doc.pipe(res);

    doc.fontSize(22).text("AUREVIA HEALTH AUDIT REPORT", {
      align: "center",
    });

    doc.moveDown();
    doc.fontSize(14).text(`Risk Score: ${assessment.riskScore}`);
    doc.text(`Risk Level: ${assessment.riskLevel}`);
    doc.text(`Age: ${assessment.age}`);
    doc.text(`Gender: ${assessment.gender}`);
    doc.text(`BMI: ${assessment.bmi}`);
    doc.text(`Exercise Days: ${assessment.exerciseFrequency}`);
    doc.text(`Sleep Hours: ${assessment.sleepHours}`);
    doc.text(`Stress Level: ${assessment.stressLevel}`);

    doc.moveDown();
    doc.text("Generated by Aurevia Integrity Labs");

    doc.end();

  } catch (error) {
    console.error("PDF generation error:", error);
    res.status(500).json({ message: "PDF generation failed" });
  }
});

export default router;
